#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP and write Holberton School in index file
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i "/server_name _;/ a rewrite ^/redirect_me https://github.com/RobARC permanent;" /etc/nginx/sites-available/default
service nginx restart
