#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP and write Holberton School in index file
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com permanent;' /etc/nginx/sites-available/default
service nginx start
