#!/usr/bin/env bash
# install ngix, setup it up on port 80 HTTP and write Holberton School in index file
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
URL="\\\trewrite ^/redirect_me https://github.com/RobARC permanent;"
service nginx start
