#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
apt-get -y update
apt-get -y install nginx
echo 'Holberton School' > /var/www/html/index.html
sed -i "/server_name _;/ a rewrite ^/redirect_me https://github.com/RobARC permanent;" /etc/nginx/sites-available/default
service nginx restart
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/ a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx restart

