#!/usr/bin/env bash
# Install and configure HAproxy on your load-balance server.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo "
frontend roberth.tech
	 bind 0:80
	 mode http
	 default_backend web_servers

backend web_servers
	balance roundrobin
	option forwardfor
	server 2474-web-01 34.74.177.231:80 check
	server 2474-web-02 54.157.57.160:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
