#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 100.

# Requirements:

# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

var=1

while [ $var -le 100 ]
do
	if (( var % 5 == 0 && var % 3 == 0 ))
	then
	echo "FizzBuzz"
	elif (( var % 5 == 0 ))
	then
	echo "Buzz"
	elif (( var % 3 == 0 ))
	then
	echo "Fizz"
	else
	echo "$var"
	fi
	var=$(( var + 1 ))
done	
