#!/usr/bin/env bash
# script that displays Holberton School 10 times, but for the 9th iteration,
# displays Holberton School and then Hi on a new line.

var=10

while [ $var -gt 0 ]
do
	
	if [ $var -eq 1 ]
	then
		echo "Hi"
	fi
	echo "Holberton School"
	var=$(( var - 1))
done
