#!/usr/bin/env bash
#write a Bash script that displays numbers from 1 to 20 and:

#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

var=20

while [ $var -gt 0 ]
	do

	case $var in
		
		"4") echo "bad luck from China"
		"9") echo "bad luck from Japan"
		"17") echo "bad luck from Italy"
	esac
	echo "Holberton Scholl"
	
	var=$(( var - 1))
done
