#!/usr/bin/env bash
#write a Bash script that displays numbers from 1 to 20 and:

#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteratio    n

hor=0
while [ $hor -le 12 ]
do
	echo "Hora: $hor"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		min=$(( min  + 1 ))
	done
	hor=$(( hor  + 1 ))
done
